#!/bin/bash

JAVA_VERSION="1.7"
JAVA_TARGET_VERSION="1.7"
SOURCE_PATH="src"
CLASS_PATH="bin"

JC_DEBUG_OPTIONS="-g -Xlint:unchecked"
JC_JAVAV_OPTIONS="-source $JAVA_VERSION -target $JAVA_TARGET_VERSION"
JC_PATH_OPTIONS="-sourcepath $SOURCE_PATH -classpath $CLASS_PATH -d $CLASS_PATH"
JC_OPTIMIZATION_OPTIONS="-O"

JC_OPTIONS="$JC_PATH_OPTIONS $JC_JAVAV_OPTIONS $JC_OPTIMIZATION_OPTIONS"

############## Darwin kernel detection ##############

MAC=false
unamestr=`uname`

if test "$unamestr" = 'Darwin'
then
  echo "MacOSX detected: activated AppleSpecific classes."
  javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/AppleSpecific.java
  echo "Copying Quaqua library files in jar/ directory."
  cp OSes/mac/Quaqua/*.* jar
  MAC=true
fi


############## Arguments parsing ##############

WHAT_COMPILE="FidoCadJ"

for arg in $@
do
    case $arg in
        -debug)
            JAVAC_OPTIONS="$JC_OPTIONS $JC_DEBUG_OPTIONS"
                ;;
        -mac)
            if test ! MAC
            then
                echo "MacOSX detected: activated AppleSpecific classes."
                javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/AppleSpecific.java
                echo "Copying Quaqua library files in jar/ directory."
                cp OSes/mac/Quaqua/*.* jar
            fi
                ;;
        -applets)
            WHAT_COMPILE="applets"
                ;;
        -all)
            WHAT_COMPILE="all"
                ;;
        *)
            echo "Unrecognized option."
            exit -1
                ;;
    esac
done

############## Do compile ##############

case $WHAT_COMPILE in
    applets)
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoReadApplet.java
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoCadApplet.java
            ;;
    all)
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoMain.java
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoReadApplet.java
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoCadApplet.java
            ;;
    FidoCadJ)
        javac $JC_OPTIONS ./src/net/sourceforge/fidocadj/FidoMain.java
            ;;
esac

exit 0
